lib: [
  "_build/install/default/lib/alcotest-lwt/META"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.a"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cma"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmi"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmt"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmti"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmx"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmxa"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.cmxs"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.ml"
  "_build/install/default/lib/alcotest-lwt/alcotest_lwt.mli"
  "_build/install/default/lib/alcotest-lwt/dune-package"
  "_build/install/default/lib/alcotest-lwt/opam"
]
doc: [
  "_build/install/default/doc/alcotest-lwt/CHANGES.md"
  "_build/install/default/doc/alcotest-lwt/LICENSE.md"
  "_build/install/default/doc/alcotest-lwt/README.md"
]
