lib: [
  "_build/install/default/lib/configurator/META"
  "_build/install/default/lib/configurator/configurator.a"
  "_build/install/default/lib/configurator/configurator.cma"
  "_build/install/default/lib/configurator/configurator.cmi"
  "_build/install/default/lib/configurator/configurator.cmt"
  "_build/install/default/lib/configurator/configurator.cmti"
  "_build/install/default/lib/configurator/configurator.cmx"
  "_build/install/default/lib/configurator/configurator.cmxa"
  "_build/install/default/lib/configurator/configurator.cmxs"
  "_build/install/default/lib/configurator/configurator.ml"
  "_build/install/default/lib/configurator/configurator.mli"
  "_build/install/default/lib/configurator/dune-package"
  "_build/install/default/lib/configurator/opam"
]
doc: [
  "_build/install/default/doc/configurator/LICENSE.txt"
  "_build/install/default/doc/configurator/README.org"
]
