lib: [
  "_build/install/default/lib/digestif/META"
  "_build/install/default/lib/digestif/c/.private/digestif_bi.cmi"
    {"c/.private/digestif_bi.cmi"}
  "_build/install/default/lib/digestif/c/.private/digestif_by.cmi"
    {"c/.private/digestif_by.cmi"}
  "_build/install/default/lib/digestif/c/.private/digestif_conv.cmi"
    {"c/.private/digestif_conv.cmi"}
  "_build/install/default/lib/digestif/c/.private/digestif_eq.cmi"
    {"c/.private/digestif_eq.cmi"}
  "_build/install/default/lib/digestif/c/.private/digestif_hash.cmi"
    {"c/.private/digestif_hash.cmi"}
  "_build/install/default/lib/digestif/c/.private/digestif_native.cmi"
    {"c/.private/digestif_native.cmi"}
  "_build/install/default/lib/digestif/c/digestif.cmi" {"c/digestif.cmi"}
  "_build/install/default/lib/digestif/c/digestif.cmt" {"c/digestif.cmt"}
  "_build/install/default/lib/digestif/c/digestif.cmx" {"c/digestif.cmx"}
  "_build/install/default/lib/digestif/c/digestif.ml" {"c/digestif.ml"}
  "_build/install/default/lib/digestif/c/digestif_bi.cmt"
    {"c/digestif_bi.cmt"}
  "_build/install/default/lib/digestif/c/digestif_bi.cmx"
    {"c/digestif_bi.cmx"}
  "_build/install/default/lib/digestif/c/digestif_bi.ml" {"c/digestif_bi.ml"}
  "_build/install/default/lib/digestif/c/digestif_by.cmt"
    {"c/digestif_by.cmt"}
  "_build/install/default/lib/digestif/c/digestif_by.cmx"
    {"c/digestif_by.cmx"}
  "_build/install/default/lib/digestif/c/digestif_by.ml" {"c/digestif_by.ml"}
  "_build/install/default/lib/digestif/c/digestif_c.a" {"c/digestif_c.a"}
  "_build/install/default/lib/digestif/c/digestif_c.cma" {"c/digestif_c.cma"}
  "_build/install/default/lib/digestif/c/digestif_c.cmxa"
    {"c/digestif_c.cmxa"}
  "_build/install/default/lib/digestif/c/digestif_c.cmxs"
    {"c/digestif_c.cmxs"}
  "_build/install/default/lib/digestif/c/digestif_conv.cmt"
    {"c/digestif_conv.cmt"}
  "_build/install/default/lib/digestif/c/digestif_conv.cmx"
    {"c/digestif_conv.cmx"}
  "_build/install/default/lib/digestif/c/digestif_conv.ml"
    {"c/digestif_conv.ml"}
  "_build/install/default/lib/digestif/c/digestif_eq.cmt"
    {"c/digestif_eq.cmt"}
  "_build/install/default/lib/digestif/c/digestif_eq.cmx"
    {"c/digestif_eq.cmx"}
  "_build/install/default/lib/digestif/c/digestif_eq.ml" {"c/digestif_eq.ml"}
  "_build/install/default/lib/digestif/c/digestif_hash.cmt"
    {"c/digestif_hash.cmt"}
  "_build/install/default/lib/digestif/c/digestif_hash.cmx"
    {"c/digestif_hash.cmx"}
  "_build/install/default/lib/digestif/c/digestif_hash.ml"
    {"c/digestif_hash.ml"}
  "_build/install/default/lib/digestif/c/digestif_native.cmt"
    {"c/digestif_native.cmt"}
  "_build/install/default/lib/digestif/c/digestif_native.cmx"
    {"c/digestif_native.cmx"}
  "_build/install/default/lib/digestif/c/digestif_native.ml"
    {"c/digestif_native.ml"}
  "_build/install/default/lib/digestif/digestif.cmi"
  "_build/install/default/lib/digestif/digestif.cmti"
  "_build/install/default/lib/digestif/digestif.mli"
  "_build/install/default/lib/digestif/dune-package"
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_blake2b.cmi"
    {"ocaml/.private/baijiu_blake2b.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_blake2s.cmi"
    {"ocaml/.private/baijiu_blake2s.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_md5.cmi"
    {"ocaml/.private/baijiu_md5.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_rmd160.cmi"
    {"ocaml/.private/baijiu_rmd160.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_sha1.cmi"
    {"ocaml/.private/baijiu_sha1.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_sha224.cmi"
    {"ocaml/.private/baijiu_sha224.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_sha256.cmi"
    {"ocaml/.private/baijiu_sha256.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_sha384.cmi"
    {"ocaml/.private/baijiu_sha384.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_sha512.cmi"
    {"ocaml/.private/baijiu_sha512.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/baijiu_whirlpool.cmi"
    {"ocaml/.private/baijiu_whirlpool.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/digestif_bi.cmi"
    {"ocaml/.private/digestif_bi.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/digestif_by.cmi"
    {"ocaml/.private/digestif_by.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/digestif_conv.cmi"
    {"ocaml/.private/digestif_conv.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/digestif_eq.cmi"
    {"ocaml/.private/digestif_eq.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/digestif_hash.cmi"
    {"ocaml/.private/digestif_hash.cmi"}
  "_build/install/default/lib/digestif/ocaml/.private/xor.cmi"
    {"ocaml/.private/xor.cmi"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2b.cmt"
    {"ocaml/baijiu_blake2b.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2b.cmx"
    {"ocaml/baijiu_blake2b.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2b.ml"
    {"ocaml/baijiu_blake2b.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2s.cmt"
    {"ocaml/baijiu_blake2s.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2s.cmx"
    {"ocaml/baijiu_blake2s.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_blake2s.ml"
    {"ocaml/baijiu_blake2s.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_md5.cmt"
    {"ocaml/baijiu_md5.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_md5.cmx"
    {"ocaml/baijiu_md5.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_md5.ml"
    {"ocaml/baijiu_md5.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_rmd160.cmt"
    {"ocaml/baijiu_rmd160.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_rmd160.cmx"
    {"ocaml/baijiu_rmd160.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_rmd160.ml"
    {"ocaml/baijiu_rmd160.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha1.cmt"
    {"ocaml/baijiu_sha1.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha1.cmx"
    {"ocaml/baijiu_sha1.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha1.ml"
    {"ocaml/baijiu_sha1.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha224.cmt"
    {"ocaml/baijiu_sha224.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha224.cmx"
    {"ocaml/baijiu_sha224.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha224.ml"
    {"ocaml/baijiu_sha224.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha256.cmt"
    {"ocaml/baijiu_sha256.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha256.cmx"
    {"ocaml/baijiu_sha256.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha256.ml"
    {"ocaml/baijiu_sha256.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha384.cmt"
    {"ocaml/baijiu_sha384.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha384.cmx"
    {"ocaml/baijiu_sha384.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha384.ml"
    {"ocaml/baijiu_sha384.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha512.cmt"
    {"ocaml/baijiu_sha512.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha512.cmx"
    {"ocaml/baijiu_sha512.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_sha512.ml"
    {"ocaml/baijiu_sha512.ml"}
  "_build/install/default/lib/digestif/ocaml/baijiu_whirlpool.cmt"
    {"ocaml/baijiu_whirlpool.cmt"}
  "_build/install/default/lib/digestif/ocaml/baijiu_whirlpool.cmx"
    {"ocaml/baijiu_whirlpool.cmx"}
  "_build/install/default/lib/digestif/ocaml/baijiu_whirlpool.ml"
    {"ocaml/baijiu_whirlpool.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif.cmi"
    {"ocaml/digestif.cmi"}
  "_build/install/default/lib/digestif/ocaml/digestif.cmt"
    {"ocaml/digestif.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif.cmx"
    {"ocaml/digestif.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif.ml"
    {"ocaml/digestif.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_bi.cmt"
    {"ocaml/digestif_bi.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif_bi.cmx"
    {"ocaml/digestif_bi.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif_bi.ml"
    {"ocaml/digestif_bi.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_by.cmt"
    {"ocaml/digestif_by.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif_by.cmx"
    {"ocaml/digestif_by.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif_by.ml"
    {"ocaml/digestif_by.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_conv.cmt"
    {"ocaml/digestif_conv.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif_conv.cmx"
    {"ocaml/digestif_conv.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif_conv.ml"
    {"ocaml/digestif_conv.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_eq.cmt"
    {"ocaml/digestif_eq.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif_eq.cmx"
    {"ocaml/digestif_eq.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif_eq.ml"
    {"ocaml/digestif_eq.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_hash.cmt"
    {"ocaml/digestif_hash.cmt"}
  "_build/install/default/lib/digestif/ocaml/digestif_hash.cmx"
    {"ocaml/digestif_hash.cmx"}
  "_build/install/default/lib/digestif/ocaml/digestif_hash.ml"
    {"ocaml/digestif_hash.ml"}
  "_build/install/default/lib/digestif/ocaml/digestif_ocaml.a"
    {"ocaml/digestif_ocaml.a"}
  "_build/install/default/lib/digestif/ocaml/digestif_ocaml.cma"
    {"ocaml/digestif_ocaml.cma"}
  "_build/install/default/lib/digestif/ocaml/digestif_ocaml.cmxa"
    {"ocaml/digestif_ocaml.cmxa"}
  "_build/install/default/lib/digestif/ocaml/digestif_ocaml.cmxs"
    {"ocaml/digestif_ocaml.cmxs"}
  "_build/install/default/lib/digestif/ocaml/xor.cmt" {"ocaml/xor.cmt"}
  "_build/install/default/lib/digestif/ocaml/xor.cmx" {"ocaml/xor.cmx"}
  "_build/install/default/lib/digestif/ocaml/xor.ml" {"ocaml/xor.ml"}
  "_build/install/default/lib/digestif/opam"
  "_build/install/default/lib/digestif/rakia/librakia_stubs.a"
    {"rakia/librakia_stubs.a"}
  "_build/install/default/lib/digestif/rakia/rakia.a" {"rakia/rakia.a"}
  "_build/install/default/lib/digestif/rakia/rakia.cma" {"rakia/rakia.cma"}
  "_build/install/default/lib/digestif/rakia/rakia.cmi" {"rakia/rakia.cmi"}
  "_build/install/default/lib/digestif/rakia/rakia.cmt" {"rakia/rakia.cmt"}
  "_build/install/default/lib/digestif/rakia/rakia.cmx" {"rakia/rakia.cmx"}
  "_build/install/default/lib/digestif/rakia/rakia.cmxa" {"rakia/rakia.cmxa"}
  "_build/install/default/lib/digestif/rakia/rakia.cmxs" {"rakia/rakia.cmxs"}
  "_build/install/default/lib/digestif/rakia/rakia.ml" {"rakia/rakia.ml"}
]
stublibs: "_build/install/default/lib/stublibs/dllrakia_stubs.so"
doc: [
  "_build/install/default/doc/digestif/CHANGES.md"
  "_build/install/default/doc/digestif/LICENSE.md"
  "_build/install/default/doc/digestif/README.md"
]
